<?xml version="1.0"?>
 <robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="arm_base_len" value="0.1" />
    <xacro:property name="arm_base_w" value="0.1" />
    <xacro:property name="arm_base_h" value="0.02" />

    <xacro:property name="forearm_rad" value="0.02" />
    <xacro:property name="forearm_len" value="0.3" />

    <link name="world_arm"/>
    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_len} ${arm_base_w}  ${arm_base_h}"/>
            </geometry>            
            <origin xyz="0 0 ${arm_base_h / 2}" rpy="0 0 0"/>
        <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_len} ${arm_base_w}  ${arm_base_h}"/>
            </geometry>            
            <origin xyz="0 0 ${arm_base_h / 2}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="0.5" l="${2*arm_base_len}" w="${2*arm_base_w}" h="${2*arm_base_h}"
        xyz="0 0 ${arm_base_h / 2}" rpy="0 0 0"/>
    </link> 
    <joint name="base_world_arm" type="fixed">
        <parent link="world_arm" />
        <child link="arm_base_link" />
        <origin xyz="0 0 0.0" rpy="0 0 0"/>
    </joint>


    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_rad}" length="${forearm_len}"/>
            </geometry>
            <origin xyz="0 0 ${forearm_len / 2}" rpy="0.0 0.0 0.0"/>
            <material name="yellow"/> 
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${forearm_rad}" length="${forearm_len}"/>
            </geometry>
            <origin xyz="0 0 ${forearm_len / 2}" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*forearm_rad}" h="${2*forearm_len}" 
            xyz="0 0 ${forearm_len / 2}" rpy="0.0 0.0 0.0" />
    </link>
    <joint name="forearm_arm_base_joint" type="revolute">
        <origin xyz="0.0 0.0 ${arm_base_h}" rpy="0.0 0.0 0.0"/>
        <parent link="arm_base_link"/>
        <child link="forearm_link"/>
        <axis xyz="0 1 0"/>
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100"/>
        <dynamics friction="0.05" damping="0.1"/>
    </joint>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_rad}" length="${forearm_len}"/>
            </geometry>
            <origin xyz="0 0 ${forearm_len / 2}" rpy="0.0 0.0 0.0"/>
            <material name="Blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${forearm_rad}" length="${forearm_len}"/>
            </geometry>
            <origin xyz="0 0 ${forearm_len / 2}" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*forearm_rad}" h="${2*forearm_len}" 
            xyz="0 0 ${forearm_len / 2}" rpy="0.0 0.0 0.0" />
    </link>
    <joint name="hand_forearm_arm_joint" type="revolute">
        <origin xyz="0.0 0.0 ${forearm_len}" rpy="0.0 0.0 0.0"/>
        <parent link="forearm_link"/>
        <child link="hand_link"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100"/>
        <dynamics friction="0.05" damping="0.1"/>
    </joint>

</robot>