<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_len" value="0.01"/>
    <xacro:property name="camera_w" value="0.1"/>
    <xacro:property name="camera_h" value="0.05"/>

    <gazebo reference ="camera_link">
        <material>Gazebo/Grey</material>
        <sensor name="camera_sensor" type="camera">
            <!-- all sensors need these three tags -->
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10.0</update_rate>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <!-- Set TF frame name. If empty, defaults to link name -->
                <frame_name>camera_link_optical</frame_name>
            </plugin>
        </sensor>
    </gazebo>

    <link name="camera_link">
        <visual>
            <geometry>
                <!-- <box size="0.1 0.1 0.05"/>  means 10cm x 10cm x 5cm-->
                <box size="${camera_len} ${camera_w} ${camera_h}"/> 
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_len} ${camera_w} ${camera_h}"/>
            </geometry>            
        </collision>
        <xacro:box_inertia m="0.1" l="${camera_len}" w="${camera_w}" h="${camera_h}"
            xyz="0 0 0" rpy="0 0 0"/>
    </link>
    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${(base_len + camera_len) / 2} 0 ${base_h / 2}" rpy="0.0 0.0 0.0"/>
    </joint>

     <!-- This bit of code is for making rviz/gazebo camera positioning compatible with OpenCV for use later -->
    <link name="camera_link_optical"/>
    <joint name="camera_optical_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="${-pi/2} 0.0 ${-pi/2}"/>
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <axis xyz="0.0 0.0 0.0"/>
        <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
    </joint>
    <!-- end opencv bit -->
</robot> 