<?xml version="1.0"?>
  <robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_prop.xacro"/>
    <xacro:property name="base_len" value="1.0"/>

      <link name="world" />

      <link name="base_link">
          <visual>
              <geometry>
                  <box size="${base_len} 0.4 0.2" />
              </geometry>
              <origin xyz="-3 -2 0.1" rpy="0 0 0" />
              <material name="blue" />
          </visual>
      </link>

        <joint name="base_world" type="fixed">
            <parent link="world" />
            <child link="base_link" />
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
        </joint>

    <link name="right_wheel_link">
          <visual>
              <geometry>
                  <cylinder radius="0.1" length="0.05" />
              </geometry>
              <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
              <material name="grey" />
          </visual>
    </link>
    <xacro:macro name="macro_wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="0.1" length="0.05" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 1.0 1.0" />
                <material name="grey" />
            </visual>
      </link>
    </xacro:macro>
    <xacro:macro_wheel_link prefix="back"/>
    <joint name="base_back_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="back_wheel_link"/>
        <origin xyz="${-base_len / 4.0} -0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
      </joint>

    <joint name="base_right_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="right_wheel_link"/>
      <origin xyz="${-base_len / 4.0} -0.225 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
    </joint>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="grey" />
        </visual>
    </link>
    
    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="-0.15 0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint> 

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
    </link>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_len / 3.0} 0 -0.05" rpy="0 0 0" />
    </joint>

    <link name="new_link">
        <visual>
            <geometry>
                <sphere radius="0.5"/>
            </geometry>
        </visual>
    </link>
    <joint name="new_world" type="fixed">
        <parent link="world" />
        <child link="new_link" />
        <origin xyz="3 2 -0.05" rpy="0 0 0" />
    </joint>

    <link name="new_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.01" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="grey" />
        </visual>
    </link>
    <joint name="new_left_wheel_joint" type="continuous">
        <parent link="new_link" />
        <child link="new_wheel_link" />
        <origin xyz="-0.15 0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint> 

  </robot>